version: '3.10'

services:
  web:
    container_name: web
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis



  redis:
    container_name: redis
    image: redis:5
    ports:
      - "6379:6379"


